name: build

on:
  push: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show ref
        run: |
          echo "$GITHUB_REF"
      - name: Build docker image
        run: |
          docker build -t ghcr.io/alephdata/translate:${GITHUB_SHA} .
      - name: Push docker image (master)
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/alephdata/translate:${GITHUB_SHA}
          docker tag ghcr.io/alephdata/translate:${GITHUB_SHA} ghcr.io/alephdata/translate:latest
          docker push ghcr.io/alephdata/translate:latest
