name: build

on:
  push: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show ref
        run: |
          echo "$GITHUB_REF"
      - name: Build docker image
        run: |
          docker build -t alephdata/translate:${GITHUB_SHA} .
          make build
      - name: Push docker image (master)
        run: |
          docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
          docker push alephdata/translate:${GITHUB_SHA}
          make push
